#!/usr/bin/env bash
# Installs the RustDAW song-import worker on macOS or Ubuntu.
#
# Creates a self-contained Python virtualenv with Demucs, basic-pitch, yt-dlp and
# librosa under the worker data directory, copies the worker in, and drops a
# launcher that RustDAW discovers automatically. Re-runnable: it updates an
# existing install in place.
#
# Usage: crates/daw-songimport/worker/install.sh
#
# The heavy model checkpoints (~2-3 GB for Demucs) are NOT downloaded here; they
# download on the first real import. Only the code and Python packages are set up.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Resolve the data directory, matching supervisor.rs / store.py ------------
if [ -n "${CHORDS_STUDIO_DATA:-}" ]; then
  DATA_DIR="$CHORDS_STUDIO_DATA"
elif [ "$(uname -s)" = "Darwin" ]; then
  DATA_DIR="$HOME/Library/Application Support/chords-extraction"
else
  DATA_DIR="$HOME/.local/share/chords-extraction"
fi
echo "==> Worker data directory: $DATA_DIR"

# --- Pick a Python interpreter ------------------------------------------------
# The ML stack (torch, demucs, basic-pitch) has far better wheel coverage on
# Python 3.10-3.12 than on 3.13, and basic-pitch only installs on <=3.11, so
# prefer an older minor version when several are available.
PYTHON=""
for candidate in python3.11 python3.12 python3.10 python3; do
  if command -v "$candidate" >/dev/null 2>&1; then
    PYTHON="$candidate"
    break
  fi
done
if [ -z "$PYTHON" ]; then
  echo "error: python3 not found." >&2
  if [ "$(uname -s)" = "Darwin" ]; then
    echo "  Install it with: brew install python@3.11" >&2
  else
    echo "  Install it with: sudo apt install python3 python3-venv python3-pip" >&2
  fi
  exit 1
fi
echo "==> Using $($PYTHON --version 2>&1) ($PYTHON)"

if ! command -v ffmpeg >/dev/null 2>&1; then
  echo "warning: ffmpeg not found — RustDAW needs it to convert stems." >&2
  if [ "$(uname -s)" = "Darwin" ]; then
    echo "  Install it with: brew install ffmpeg" >&2
  else
    echo "  Install it with: sudo apt install ffmpeg" >&2
  fi
fi

# --- Lay out the install ------------------------------------------------------
mkdir -p "$DATA_DIR/projects" "$DATA_DIR/bin" "$DATA_DIR/app"
cp "$SCRIPT_DIR"/*.py "$DATA_DIR/app/"
cp "$SCRIPT_DIR"/requirements*.txt "$DATA_DIR/app/"

echo "==> Creating virtualenv"
VENV_PY="$DATA_DIR/venv/bin/python"
wanted_version="$($PYTHON -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
if [ -x "$VENV_PY" ]; then
  existing_version="$("$VENV_PY" -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo none)"
  if [ "$existing_version" != "$wanted_version" ]; then
    echo "    (recreating venv: was Python $existing_version, want $wanted_version)"
    rm -rf "$DATA_DIR/venv"
  fi
fi
if [ ! -x "$VENV_PY" ]; then
  "$PYTHON" -m venv "$DATA_DIR/venv"
fi
"$VENV_PY" -m pip install --upgrade pip >/dev/null

echo "==> Installing core packages (this can take several minutes)"
"$DATA_DIR/venv/bin/pip" install -r "$DATA_DIR/app/requirements.txt"

echo "==> Installing optional transcription (basic-pitch); skipped if unavailable"
if "$DATA_DIR/venv/bin/pip" install -r "$DATA_DIR/app/requirements-transcribe.txt"; then
  echo "    transcription enabled"
else
  echo "    transcription unavailable on this Python/platform — separation, tempo" >&2
  echo "    and chords still work; MIDI transcription is simply skipped." >&2
fi

# --- Write the launcher RustDAW starts ---------------------------------------
LAUNCHER="$DATA_DIR/bin/chords-studio-servers"
cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
# Starts the RustDAW song-import worker. Generated by install.sh.
export CHORDS_STUDIO_DATA="$DATA_DIR"
# RustDAW may launch this from a Finder-started app with a minimal PATH; make
# sure Homebrew's ffmpeg (needed by Demucs and the decoder) is reachable.
export PATH="/opt/homebrew/bin:/usr/local/bin:\$PATH"
exec "$DATA_DIR/venv/bin/python" "$DATA_DIR/app/server.py"
LAUNCH
chmod +x "$LAUNCHER"

# Also expose it on the discovery path RustDAW checks first, so no environment
# variable is needed for it to be found.
mkdir -p "$HOME/.local/bin"
ln -sf "$LAUNCHER" "$HOME/.local/bin/chords-studio-servers"

echo
echo "==> Done."
echo "    Launcher: $LAUNCHER"
echo "    RustDAW will find it and start it automatically on the next Import Song."
echo "    Verify the wiring without downloading models:"
echo "      \"$DATA_DIR/venv/bin/python\" \"$DATA_DIR/app/store.py\" --self-test"
